language: python
python:
  - "2.6"
  - "2.7"
branches:
  only:
    - master
install:
  - pip install pep8 --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E225 src"
script:
  - python tests.py
  - pytest tests.py