language: python
python:
  - "2.6"
  - "2.7"
branches:
  only:
    - master
install:
  - pip install pep8 --use-mirrors
  - pip install flake8 --use-mirrors
before_script:
  - pep8 --exclude=migrations --ignore=E501,E225 .
script:
  - python tests.py
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then flake8 --ignore=E501.; fi